---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    region: "us-east-1"
    aws_access_key: ""
    aws_secret_key: ""

  tasks:
  - set_fact:
      bucket: "ansible-test-bucket-{{ 500 |random(start=1, step=5) }}"
      file: "/tmp/ansible_put_object_{{ 500 |random(start=1, step=5) }}"
  # This will run through all possible scenarios for putting an object to S3 with full validation of bucket and objects.
  - name: Create a random file for testing.
    lineinfile:
      create: yes
      dest: "{{ file }}"
      line: "s3 put object test"
      state: present

  - name: PUT with no options on non-existing bucket - line 527.
    s3:
      bucket: "{{ bucket }}"
      object: "{{ file }}"
      src: "{{ file }}"
      mode: put
      region: "{{ region }}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: r
  - fail: msg='File nor bucket should exist at start of test'
    when: r is not changed

  - name: Delete the object - line 558.
    s3:
      bucket: "{{ bucket }}"
      object: "{{ file }}"
      mode: delobj
      region: "{{ region }}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: r
  - fail: msg='File should have existed and been deleted'
    when: r is not changed

  - name: PUT with no options on existing bucket - line 545.
    s3:
      bucket: "{{ bucket }}"
      object: "{{ file }}"
      src: "{{ file }}"
      mode: put
      region: "{{ region }}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: r
  - fail: msg='File should not exist.'
    when: r is not changed

  - name: PUT with overwrite=always with existing remote object - line 527.
    s3:
      bucket: "{{ bucket }}"
      object: "{{ file }}"
      src: "{{ file }}"
      mode: put
      region: "{{ region }}"
      overwrite: always
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: r
  - fail: msg='File should have existed and uploaded successfully since overwrite=always'
    when: r is not changed

  - name: PUT with overwrite=different with existing remote object - line 542.
    s3:
      bucket: "{{ bucket }}"
      object: "{{ file }}"
      src: "{{ file }}"
      mode: put
      region: "{{ region }}"
      overwrite: different
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: r
  - fail: msg='File should already exist and should fail since the files are identical'
    when: r | changed

  - name: PUT with overwrite=never with existing remote object - line 534.
    s3:
      bucket: "{{ bucket }}"
      object: "{{ file }}"
      src: "{{ file }}"
      mode: put
      region: "{{ region }}"
      overwrite: never
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: r
  - fail: msg='File should already exist and should fail since overwrite=never'
    when: r | changed

  - name: Add a random number to the test file
    lineinfile:
      dest: "{{ file }}"
      line: "{{ 50 |random(start=1, step=5) }}"
      state: present
    register: r
  - fail: msg='Pretty unlucky with this. Number must have already existed in the file.'
    when: r is not changed

  - name: PUT with overwrite=never with different existing remote object - line 534.
    s3:
      bucket: "{{ bucket }}"
      object: "{{ file }}"
      src: "{{ file }}"
      mode: put
      region: "{{ region }}"
      overwrite: never
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: r
  - fail: msg='File should already exist and should fail since overwrite=never'
    when: r | changed

  - name: PUT with overwrite=different with different existing remote object - line 543.
    s3:
      bucket: "{{ bucket }}"
      object: "{{ file }}"
      src: "{{ file }}"
      mode: put
      region: "{{ region }}"
      overwrite: different
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: r
  - fail: msg='Files should be different so upload should have succeeded.'
    when: r is not changed

  - name: Delete the object
    s3:
      bucket: "{{ bucket }}"
      object: "{{ file }}"
      mode: delobj
      region: "{{ region }}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: r
  - fail: msg='File should have existed and been deleted'
    when: r is not changed

  - name: PUT with overwrite=never with non-existing remote object - line 545.
    s3:
      bucket: "{{ bucket }}"
      object: "{{ file }}"
      src: "{{ file }}"
      mode: put
      region: "{{ region }}"
      overwrite: never
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: r
  - fail: msg='File should not already exist and should have been uploaded'
    when: r is not changed

  - name: Delete the bucket
    s3:
      bucket: "{{ bucket }}"
      mode: delete
      region: "{{ region }}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: r
  - fail: msg='Bucket and contents should have been deleted.'
    when: r is not changed